### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by willruiz** [MeLikeFish/AI-Writing-Detection#3]
**Describe the bug**

Code error message does not support Chrome version 116. (Latest version of Chrome as of September 21st, 2023). 
When running main.py with a folder of .txt files, this error appears.

<img width="905" alt="image" src="https://github.com/Nygosaki/AI-Writing-Detection/assets/46848051/b620ab9e-91da-4c98-951b-bc2daf462192">

**To Reproduce**
Run main.py while having chrome version 116

**Expected behavior**

**Output/Logs**
If applicable, add Output/Logs from the debug mode to help explain your problem.
DevTools listening on ws://127.0.0.1:50929/devtools/browser/95cd6299-cee6-4d5e-9fda-17900e790e48                                                                            Traceback (most recent call last):                                                                                                                                            File "C:\testground\AI-Writing-Detection\main.py", line 79, in <module>                                                                                                       driver = webdriver.Chrome(options=options)                                                                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                File "C:\Users\willi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__                                  super().__init__(                                                                                                                                                         File "C:\Users\willi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__                               super().__init__(                                                                                                                                                         File "C:\Users\willi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__                                 self.start_session(capabilities, browser_profile)                                                                                                                         File "C:\Users\willi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session                            response = self.execute(Command.NEW_SESSION, parameters)                                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                  File "C:\Users\willi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute                                  self.error_handler.check_response(response)                                                                                                                               File "C:\Users\willi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response                        raise exception_class(message, screen, stacktrace)                                                                                                                      selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114                          Current browser version is 116.0.5845.188 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe                                                            Stacktrace:                                                                                                                                                                 Backtrace:                                                                                                                                                                          GetHandleVerifier [0x00EEA813+48355]                                                                                                                                        (No symbol) [0x00E7C4B1]                                                                                                                                                    (No symbol) [0x00D85358]                                                                                                                                                    (No symbol) [0x00DA61AC]                                                                                                                                                    (No symbol) [0x00DA1EF3]                                                                                                                                                    (No symbol) [0x00DA0579]                                                                                                                                                    (No symbol) [0x00DD0C55]                                                                                                                                                    (No symbol) [0x00DD093C]                                                                                                                                                    (No symbol) [0x00DCA536]                                                                                                                                                    (No symbol) [0x00DA82DC]                                                                                                                                                    (No symbol) [0x00DA93DD]                                                                                                                                                    GetHandleVerifier [0x0114AABD+2539405]                                                                                                                                      GetHandleVerifier [0x0118A78F+2800735]                                                                                                                                      GetHandleVerifier [0x0118456C+2775612]                                                                                                                                      GetHandleVerifier [0x00F751E0+616112]                                                                                                                                       (No symbol) [0x00E85F8C]                                                                                                                                                    (No symbol) [0x00E82328]                                                                                                                                                    (No symbol) [0x00E8240B]                                                                                                                                                    (No symbol) [0x00E74FF7]                                                                                                                                                    BaseThreadInitThunk [0x766E7BA9+25]                                                                                                                                         RtlInitializeExceptionChain [0x7752B79B+107]                                                                                                                                RtlClearBits [0x7752B71F+191]   

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by Nygosaki** [comment]
Hey there,    
I am sorry you are facing this issue.     
In order to prevent being flagged as a bot, instead of normal chrome drivers, I use the [undetected-chromedriver](https://pypi.org/project/undetected-chromedriver/2.1.1/) library. It also allows me to not have to worry about proper driver directory setting.    
Sadly, this project supports only chrome v114 and bellow.    
You can find the download link for the correct chrome version in the [How to install](https://github.com/Nygosaki/AI-Writing-Detection#how-to-install) part of the READ.md.      
If you have any other questions, feel free to ask. Otherwise, please close the issue.

**Comment by Nygosaki** [comment]
Closing due to inactivity and an answer being provided
